### ISSUE TITLE
关于该模块的使用，是只能替代不改变通道数的卷积层吗？

### ISSUE THREAD

**Issue by Fossettely** [cheng-haha/ScConv#2]
我看文章说的是加在前一个卷积块和之后的卷积块中间，那么中间这个是直接替换为该卷积块？但是我看代码里头只有一个通道，是不能改变通道数的，那么我原本的卷积需要进行通道数的变换该如何操作，对该模块进行修改？还是加上一个1*1卷积改变通道呢。我的backbone使用的是U-Net结构，通道数是会发生变化的，我这也能替代任何一个卷积？

**Comment by cheng-haha** [comment]
是的，你可以选择1*1卷积进行升维，或者选择bottleneck结构，在ScConv前面追加1*1降维(更进一步降低参数)，在ScConv后面加入1*1conv升到你想要的维度；当然可以替换，升维操作只是trick，真正的故事是你这个模块是否真的能减少特征冗余，带来性能提升。

**Comment by cheng-haha** [comment]
是的，你可以选择11卷积进行升维，或者选择bottleneck结构，在ScConv前面追加1*1conv降维(更进一步降低参数)，在ScConv后面加入1*1conv升到你想要的维度；当然可以替换，升维操作只是trick，真正的故事是你这个模块是否真的能减少特征冗余，带来性能提升。

**Comment by cheng-haha** [comment]
是的，你可以选择11卷积进行升维，或者选择bottleneck结构，在ScConv前面追加1*1conv降维(更进一步降低参数)，在ScConv后面加入1*1conv升到你想要的维度；当然可以替换，升维操作只是trick，真正的故事是你这个模块是否真的能减少特征冗余，带来性能提升。

**Comment by Fossettely** [comment]
虽然没有达到Baseline文章中的指标，但是相比baseline在我本地跑的有两个数据集有提升，其余还跌了一点，因为我硬件资源有限改了batchsize，一直还没能跑出文章中的效果

**Comment by TryHard-LL** [comment]
> 虽然没有达到Baseline文章中的指标，但是相比baseline在我本地跑的有两个数据集有提升，其余还跌了一点，因为我硬件资源有限改了batchsize，一直还没能跑出文章中的效果

期待大哥的开源~

**Comment by Fossettely** [comment]
> 是的，你可以选择11卷积进行升维，或者选择bottleneck结构，在ScConv前面追加1_1conv降维(更进一步降低参数)，在ScConv后面加入1_1conv升到你想要的维度；当然可以替换，升维操作只是trick，真正的故事是你这个模块是否真的能减少特征冗余，带来性能提升。

我对着文章看了一下代码，代码应该没问题，替代的3*3卷积，α=1/2是准确率和计算资源的权衡最优值，如果我想为了更高的准确率可以使用3/4吗，在一分类任务中，等我跑哈结果先每个瓶颈结构的卷积都替换成这个卷积看一下

**Comment by cheng-haha** [comment]
> > 是的，你可以选择11卷积进行升维，或者选择bottleneck结构，在ScConv前面追加1_1conv降维(更进一步降低参数)，在ScConv后面加入1_1conv升到你想要的维度；当然可以替换，升维操作只是trick，真正的故事是你这个模块是否真的能减少特征冗余，带来性能提升。
> 
> 我对着文章看了一下代码，代码应该没问题，替代的3*3卷积，α=1/2是准确率和计算资源的权衡最优值，如果我想为了更高的准确率可以使用3/4吗，在一分类任务中，等我跑哈结果先每个瓶颈结构的卷积都替换成这个卷积看一下

好的，当然使用3/4可以的，1/2是他的权衡结果。如果有效果的话，麻烦跟我说一下, 能帮到你就行~

**Comment by wenxinss** [comment]
请问这个模块能当作一个即插即用的注意力机制使用吗?

**Comment by cheng-haha** [comment]
> 请问这个模块能当作一个即插即用的注意力机制使用吗?

我个人认为SRU就是一个空间注意力，CRU涉及部分通道注意力机制。

**Comment by linqingkuang** [comment]
你好，请问你是如何直接用ScConv模块 替代 带下采样操作的卷积方法的呀？还是利用其它卷积进行变换才可以将 ScConv替换所有类型的卷积吗？

**Comment by linqingkuang** [comment]
请问，你复现之后的Unet的参数量 降低还是增加了？

**Comment by cheng-haha** [comment]
> 你好，请问你是如何直接用ScConv模块 替代 带下采样操作的卷积方法的呀？还是利用其它卷积进行变换才可以将 ScConv替换所有类型的卷积吗？

可以在ScConv追加无参数化操作maxpooling or avgpooling进行下采样

**Comment by linqingkuang** [comment]
> 

谢谢大佬

**Comment by DearDreamer** [comment]
> 

请问如果要替换的卷积层的步长不是1，应该修改哪个参数？

**Comment by MrZhang-YUBO** [comment]
我替换了bottleneck中的3x3卷积，stride为2的情况加了个avgpool,但是实验下来无论alpha设1/2还是3/4效果都不如原来的好

**Comment by Dream-ai** [comment]
> 我替换了瓶颈中的3x3卷积，stride为2的情况加了个avgpool，但是实验下来无论alpha设1/2还是3/4效果都不如原来的好

可以分享一下你是怎么改的吗？

**Comment by Dream-ai** [comment]
> 虽然没有达到Baseline文章中的指标，但是相比baseline在我本地跑的有两个数据集有提升，其余还跌了一点，因为我硬件资源有限改了batchsize，一直还没能跑出文章中的效果

能否分享一下代码，万分感谢
