### ISSUE TITLE
SRU实现可能有点小问题

### ISSUE THREAD

**Issue by huihui43** [cheng-haha/ScConv#3]
你好, sru实现可能有点小问题. 文章里面是对sigmoid 后的 output做threshold, 所以对应代码里应该是reweigts, 而不是w_gamma

**Comment by cheng-haha** [comment]
是的，这样更合理点。我看着原图SRU灰色部分误以为是对通道直接mask，现已修正。还有任何问题烦请提交新的issue，非常感谢。
